{
  parserClass="com.vibrant.prismio.parser.PrismioParser"
  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Prismio"
  psiImplClassSuffix="Impl"
  psiPackage="com.vibrant.prismio.psi"
  psiImplPackage="com.vibrant.prismio.psi.impl"

  elementTypeHolderClass="com.vibrant.prismio.psi.PrismioTypes"
  elementTypeClass="com.vibrant.prismio.psi.PrismioElementType"
  tokenTypeClass="com.vibrant.prismio.psi.PrismioTokenType"
}

// Root rule - a Prismio file is just a sequence of items
prismioFile ::= item_*

LBRACE ::= "{"
RBRACE ::= "}"

block ::= LBRACE statement* RBRACE

function_decl ::= FN IDENTIFIER parameter_list block



// An item can be any top-level declaration or comment
private item_ ::= (
  KEYWORD
  | TYPE_KEYWORD
  | IDENTIFIER
  | OPERATOR
  | SEPARATOR
  | STRING_LITERAL
  | CHARACTER_LITERAL
  | BOOLEAN
  | MULTILINE_COMMENT
  | SINGLE_LINE_COMMENT
  | INTEGER
  | FLOAT
)

// Simplified grammar - just for lexical highlighting
// Full AST will be built by the C++ compiler